### ISSUE TITLE
Use Yaml/Plain JS Object/Some other DSL instead of .env in Dapp

### ISSUE THREAD

**Issue by mrfujisawa** [TempleDAO/temple#206]
Not totally sure how feasible this would be, but our .env have grown to be pretty large and this config has become pretty difficult to parse -- it is flat (without indentation) the variable names are in ALL_CAPS... its just a mess to look at.  We use .env because this is the built in method adding to the env that Vite provides.  I think it would be an improvement to use a different domain specific language that is better configs.  

A plain javascript object, or Yaml or something else would be nice.  You can imagine an environment looking something like
```
Tokens:
  Temple:
    Mainnet:
      Address:
    Rinkeby:
      Address:
    Hardhat:
      Address:
Contracts:
  TempleFraxAmmRouter:
    Mainnet:
      Address:
    Rinkeby:
      Address:
    Hardhat:
      Address:
```

Not sure what the pitfalls are of moving away from .env but it seems like it should be easy to add variables to the environment in the vite.config.ts file if we switch to callback mode https://vitejs.dev/config/#conditional-config
